/** Localités principales de Côte d'Ivoire pour le profil commercial */
export const LOCALITES_CI: string[] = [
  // Abidjan
  'Abidjan - Plateau',
  'Abidjan - Cocody',
  'Abidjan - Yopougon',
  'Abidjan - Abobo',
  'Abidjan - Adjamé',
  'Abidjan - Marcory',
  'Abidjan - Koumassi',
  'Abidjan - Port-Bouët',
  'Abidjan - Treichville',
  'Abidjan - Attécoubé',
  'Abidjan - Songon',
  'Abidjan - Bingerville',
  'Abidjan - Anyama',
  'Abidjan - Brofodoumé',
  // Autres grandes villes
  'Yamoussoukro',
  'Bouaké',
  'San-Pédro',
  'Korhogo',
  'Daloa',
  'Man',
  'Gagnoa',
  'Abengourou',
  'Divo',
  'Soubré',
  'Bondoukou',
  'Odienné',
  'Séguéla',
  'Katiola',
  'Ferkessédougou',
  'Grand-Bassam',
  'Assinie',
  'Dabou',
  'Agboville',
  'Tiassalé',
  'Adzopé',
  'Aboisso',
  'Grand-Lahou',
  'Sassandra',
  'Tabou',
  'Guiglo',
  'Duékoué',
  'Touba',
  'Boundiali',
  'Tengrela',
  'Bouna',
  'Tanda',
  'Daoukro',
  'Mbahiakro',
  'Bocanda',
  'Dimbokro',
  'Toumodi',
  'Oumé',
  'Issia',
  'Vavoua',
  'Zuénoula',
  'Sinfra',
  'Bouaflé',
  'Sakassou',
  'Béoumi',
  'Mankono',
  'Biankouma',
  'Danané',
  'Toulepleu',
  'Bangolo',
  'Lakota',
  'Guitry',
  'Fresco',
  'Jacqueville',
  'Akoupé',
  'Alépé',
  'Sikensi',
  'Autre localité',
];

export const CABINET_K2L = 'K2L Services SARL';
